"""ikas token sifreleme ve ai acik riza alanlari

Revision ID: 92ad9aed8742
Revises: eafd5ed73993
Create Date: 2026-09-28 10:38:02.591775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92ad9aed8742'
down_revision: Union[str, None] = 'eafd5ed73993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_yurtdisi_riza', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_riza_tarihi', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('ai_riza_tarihi')
        batch_op.drop_column('ai_yurtdisi_riza')

    # ### end Alembic commands ###
