"""baslangic semasi

Revision ID: eafd5ed73993
Revises: 
Create Date: 2026-09-18 22:46:23.218295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eafd5ed73993'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cilek_pazar_fiyatlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('kaynak', sa.Enum('HAL', 'ZINCIR_MARKET', 'IHRACAT', name='pazarkaynagi'), nullable=False),
    sa.Column('kalite_sinifi', sa.Enum('SOFRALIK_PREMIUM', 'SOFRALIK_STANDART', 'SANAYILIK_RECELLIK', name='kalitesinifi'), nullable=False),
    sa.Column('bolge', sa.String(), nullable=True),
    sa.Column('fiyat_kg', sa.Float(), nullable=False),
    sa.Column('hacim_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_pazar_fiyatlari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_pazar_fiyatlari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_pazar_fiyatlari_tarih'), ['tarih'], unique=False)

    op.create_table('hal_fiyatlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('urun_adi', sa.String(), nullable=False),
    sa.Column('urun_cinsi', sa.String(), nullable=True),
    sa.Column('urun_turu', sa.String(), nullable=True),
    sa.Column('fiyat_kg', sa.Float(), nullable=False),
    sa.Column('hacim_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hal_fiyatlari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hal_fiyatlari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hal_fiyatlari_tarih'), ['tarih'], unique=False)
        batch_op.create_index(batch_op.f('ix_hal_fiyatlari_urun_adi'), ['urun_adi'], unique=False)

    op.create_table('ihracat_fiyatlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('urun_adi', sa.String(), nullable=False),
    sa.Column('urun_cinsi', sa.String(), nullable=True),
    sa.Column('urun_turu', sa.String(), nullable=True),
    sa.Column('fiyat_kg', sa.Float(), nullable=False),
    sa.Column('miktar_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ihracat_fiyatlari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ihracat_fiyatlari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ihracat_fiyatlari_tarih'), ['tarih'], unique=False)
        batch_op.create_index(batch_op.f('ix_ihracat_fiyatlari_urun_adi'), ['urun_adi'], unique=False)

    op.create_table('il_kosgeb_mudurlugu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('il_kodu', sa.Integer(), nullable=False),
    sa.Column('il_adi', sa.String(), nullable=False),
    sa.Column('mudurluk_adi', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=False),
    sa.Column('adres', sa.String(), nullable=False),
    sa.Column('eposta', sa.String(), nullable=True),
    sa.Column('ek_mudurlukler', sa.JSON(), nullable=True),
    sa.Column('kaynak_url', sa.String(), nullable=False),
    sa.Column('dogrulama_tarihi', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('il_kosgeb_mudurlugu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_il_kosgeb_mudurlugu_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_il_kosgeb_mudurlugu_il_adi'), ['il_adi'], unique=True)
        batch_op.create_index(batch_op.f('ix_il_kosgeb_mudurlugu_il_kodu'), ['il_kodu'], unique=True)

    op.create_table('il_tarim_mudurlugu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('il_kodu', sa.Integer(), nullable=False),
    sa.Column('il_adi', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=True),
    sa.Column('adres', sa.String(), nullable=True),
    sa.Column('eposta', sa.String(), nullable=True),
    sa.Column('kaynak_url', sa.String(), nullable=False),
    sa.Column('url_dogrulandi', sa.Boolean(), nullable=False),
    sa.Column('dogrulama_tarihi', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('il_tarim_mudurlugu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_il_tarim_mudurlugu_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_il_tarim_mudurlugu_il_adi'), ['il_adi'], unique=True)
        batch_op.create_index(batch_op.f('ix_il_tarim_mudurlugu_il_kodu'), ['il_kodu'], unique=True)

    op.create_table('kurum_iletisim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum', sa.String(), nullable=False),
    sa.Column('kurum_tam_ad', sa.String(), nullable=True),
    sa.Column('cagri_merkezi_no', sa.String(), nullable=True),
    sa.Column('genel_merkez_no', sa.String(), nullable=True),
    sa.Column('calisma_saatleri', sa.String(), nullable=True),
    sa.Column('adres', sa.String(), nullable=True),
    sa.Column('web_sitesi', sa.String(), nullable=True),
    sa.Column('eposta', sa.String(), nullable=True),
    sa.Column('kaynak_url', sa.String(), nullable=False),
    sa.Column('dogrulama_tarihi', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kurum_iletisim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kurum_iletisim_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kurum_iletisim_kurum'), ['kurum'], unique=True)

    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anahtar', sa.String(), nullable=True),
    sa.Column('deger', sa.Float(), nullable=True),
    sa.Column('birim', sa.String(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_indicators_anahtar'), ['anahtar'], unique=True)
        batch_op.create_index(batch_op.f('ix_macro_indicators_id'), ['id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'BUSINESS', 'ENTERPRISE', name='plantype'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('sector_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sektor', sa.String(), nullable=True),
    sa.Column('stok_maliyeti_oran_min', sa.Float(), nullable=True),
    sa.Column('stok_maliyeti_oran_max', sa.Float(), nullable=True),
    sa.Column('reklam_oran_min', sa.Float(), nullable=True),
    sa.Column('reklam_oran_max', sa.Float(), nullable=True),
    sa.Column('net_kar_orani', sa.Float(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sector_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_benchmarks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_benchmarks_sektor'), ['sektor'], unique=True)

    op.create_table('tesvikler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurum', sa.String(), nullable=True),
    sa.Column('baslik', sa.String(), nullable=True),
    sa.Column('ozet', sa.Text(), nullable=True),
    sa.Column('detay', sa.Text(), nullable=True),
    sa.Column('hedef_kitle', sa.String(), nullable=True),
    sa.Column('kaynak_url', sa.String(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('baslama_tarihi', sa.DateTime(), nullable=True),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('tesvil_tutari', sa.String(), nullable=True),
    sa.Column('basin_orzu', sa.Float(), nullable=True),
    sa.Column('uygunluk_kriterleri', sa.JSON(), nullable=True),
    sa.Column('tutari_min', sa.Float(), nullable=True),
    sa.Column('tutari_max', sa.Float(), nullable=True),
    sa.Column('tutari_hesaplama_kriteri', sa.String(), nullable=True),
    sa.Column('tutari_hesaplama_formulu', sa.String(), nullable=True),
    sa.Column('basvuru_sartlari', sa.JSON(), nullable=True),
    sa.Column('gerekli_belgeler', sa.JSON(), nullable=True),
    sa.Column('basvuru_yeri', sa.String(), nullable=True),
    sa.Column('basvuru_suresi', sa.String(), nullable=True),
    sa.Column('destek_verilme_suresi', sa.String(), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=True),
    sa.Column('durum_notu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kaynak_url')
    )
    with op.batch_alter_table('tesvikler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tesvikler_baslik'), ['baslik'], unique=False)
        batch_op.create_index(batch_op.f('ix_tesvikler_guncelleme_tarihi'), ['guncelleme_tarihi'], unique=False)
        batch_op.create_index(batch_op.f('ix_tesvikler_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tesvikler_kurum'), ['kurum'], unique=False)

    op.create_table('cilek_parseller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('ortam_tipi', sa.Enum('SERA', 'ACIK_TARLA', name='ortamtipi'), nullable=True),
    sa.Column('alan_dekar', sa.Float(), nullable=True),
    sa.Column('cesit', sa.String(), nullable=True),
    sa.Column('dikim_tarihi', sa.Date(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('enlem', sa.Float(), nullable=True),
    sa.Column('boylam', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_parseller', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_parseller_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_parseller_org_id'), ['org_id'], unique=False)

    op.create_table('cilek_soguk_zincir_okumalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('depo_adi', sa.String(), nullable=False),
    sa.Column('sicaklik', sa.Float(), nullable=True),
    sa.Column('hedef_sicaklik_min', sa.Float(), nullable=True),
    sa.Column('hedef_sicaklik_max', sa.Float(), nullable=True),
    sa.Column('olcum_zamani', sa.DateTime(), nullable=True),
    sa.Column('parti_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_soguk_zincir_okumalari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_soguk_zincir_okumalari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_soguk_zincir_okumalari_olcum_zamani'), ['olcum_zamani'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_soguk_zincir_okumalari_org_id'), ['org_id'], unique=False)

    op.create_table('financial_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('sektor', sa.String(), nullable=True),
    sa.Column('bolge', sa.String(), nullable=True),
    sa.Column('calisan_sayisi', sa.Integer(), nullable=True),
    sa.Column('yillik_ciro', sa.Float(), nullable=True),
    sa.Column('hedefler', sa.JSON(), nullable=True),
    sa.Column('giderler', sa.JSON(), nullable=True),
    sa.Column('ilk_yil_mi', sa.Boolean(), nullable=True),
    sa.Column('arazi_buyuklugu_dekar', sa.Float(), nullable=True),
    sa.Column('urun_turu', sa.String(), nullable=True),
    sa.Column('tarim_kategori', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_profiles_org_id'), ['org_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_financial_profiles_sektor'), ['sektor'], unique=False)

    op.create_table('ikas_baglanti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('oauth_state', sa.String(), nullable=True),
    sa.Column('baglanti_durumu', sa.String(), nullable=True),
    sa.Column('son_senkron_zamani', sa.DateTime(), nullable=True),
    sa.Column('son_senkron_hata', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ikas_baglanti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ikas_baglanti_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ikas_baglanti_org_id'), ['org_id'], unique=True)

    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queries_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('cilek_fertigasyon_tanklari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsel_id', sa.Integer(), nullable=False),
    sa.Column('tank_tipi', sa.Enum('AZOT', 'FOSFOR', 'POTASYUM', name='tanktipi'), nullable=False),
    sa.Column('kapasite_litre', sa.Float(), nullable=False),
    sa.Column('doluluk_litre', sa.Float(), nullable=True),
    sa.Column('son_guncelleme', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parsel_id'], ['cilek_parseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_fertigasyon_tanklari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_fertigasyon_tanklari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_fertigasyon_tanklari_parsel_id'), ['parsel_id'], unique=False)

    op.create_table('cilek_gider_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsel_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.Enum('FIDE', 'GUBRE', 'ILAC', 'MAZOT', 'ISCILIK', 'SULAMA_ENERJI', 'AMBALAJ', 'DIGER', name='giderkategorisi'), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('aciklama', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parsel_id'], ['cilek_parseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_gider_kalemleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_gider_kalemleri_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_gider_kalemleri_parsel_id'), ['parsel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_gider_kalemleri_tarih'), ['tarih'], unique=False)

    op.create_table('cilek_hasat_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsel_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('isci_adi', sa.String(), nullable=True),
    sa.Column('toplanan_kasa', sa.Float(), nullable=False),
    sa.Column('kasa_agirlik_kg', sa.Float(), nullable=True),
    sa.Column('sure_saat', sa.Float(), nullable=True),
    sa.Column('saatlik_ucret', sa.Float(), nullable=True),
    sa.Column('kalite_sinifi', sa.Enum('SOFRALIK_PREMIUM', 'SOFRALIK_STANDART', 'SANAYILIK_RECELLIK', name='kalitesinifi'), nullable=True),
    sa.ForeignKeyConstraint(['parsel_id'], ['cilek_parseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_hasat_kayitlari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_hasat_kayitlari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_hasat_kayitlari_parsel_id'), ['parsel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_hasat_kayitlari_tarih'), ['tarih'], unique=False)

    op.create_table('cilek_ilaclamalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsel_id', sa.Integer(), nullable=False),
    sa.Column('ilac_adi', sa.String(), nullable=False),
    sa.Column('etken_madde', sa.String(), nullable=True),
    sa.Column('uygulama_tarihi', sa.DateTime(), nullable=False),
    sa.Column('phi_gun', sa.Integer(), nullable=False),
    sa.Column('doz', sa.String(), nullable=True),
    sa.Column('uygulayan', sa.String(), nullable=True),
    sa.Column('hedef', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parsel_id'], ['cilek_parseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_ilaclamalar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_ilaclamalar_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_ilaclamalar_parsel_id'), ['parsel_id'], unique=False)

    op.create_table('cilek_sensor_okumalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsel_id', sa.Integer(), nullable=False),
    sa.Column('sensor_tipi', sa.Enum('TOPRAK_NEMI', 'TOPRAK_EC', 'HAVA_SICAKLIGI', 'YAS_HAZNE_SICAKLIGI', 'NISPI_NEM', 'SERA_SIRKULASYON', name='sensortipi'), nullable=False),
    sa.Column('deger', sa.Float(), nullable=False),
    sa.Column('birim', sa.String(), nullable=True),
    sa.Column('olcum_zamani', sa.DateTime(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parsel_id'], ['cilek_parseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_sensor_okumalari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_sensor_okumalari_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_sensor_okumalari_olcum_zamani'), ['olcum_zamani'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_sensor_okumalari_parsel_id'), ['parsel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_sensor_okumalari_sensor_tipi'), ['sensor_tipi'], unique=False)

    op.create_table('cilek_sulama_donguleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsel_id', sa.Integer(), nullable=False),
    sa.Column('son_sulama_zamani', sa.DateTime(), nullable=True),
    sa.Column('sonraki_sulama_zamani', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'SULUYOR', 'TAMAMLANDI', 'HATA', name='sulamadurumu'), nullable=True),
    sa.Column('verilen_su_ph', sa.Float(), nullable=True),
    sa.Column('verilen_su_ec', sa.Float(), nullable=True),
    sa.Column('verilen_su_litre', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parsel_id'], ['cilek_parseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cilek_sulama_donguleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cilek_sulama_donguleri_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cilek_sulama_donguleri_parsel_id'), ['parsel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cilek_sulama_donguleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_sulama_donguleri_parsel_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_sulama_donguleri_id'))

    op.drop_table('cilek_sulama_donguleri')
    with op.batch_alter_table('cilek_sensor_okumalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_sensor_okumalari_sensor_tipi'))
        batch_op.drop_index(batch_op.f('ix_cilek_sensor_okumalari_parsel_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_sensor_okumalari_olcum_zamani'))
        batch_op.drop_index(batch_op.f('ix_cilek_sensor_okumalari_id'))

    op.drop_table('cilek_sensor_okumalari')
    with op.batch_alter_table('cilek_ilaclamalar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_ilaclamalar_parsel_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_ilaclamalar_id'))

    op.drop_table('cilek_ilaclamalar')
    with op.batch_alter_table('cilek_hasat_kayitlari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_hasat_kayitlari_tarih'))
        batch_op.drop_index(batch_op.f('ix_cilek_hasat_kayitlari_parsel_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_hasat_kayitlari_id'))

    op.drop_table('cilek_hasat_kayitlari')
    with op.batch_alter_table('cilek_gider_kalemleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_gider_kalemleri_tarih'))
        batch_op.drop_index(batch_op.f('ix_cilek_gider_kalemleri_parsel_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_gider_kalemleri_id'))

    op.drop_table('cilek_gider_kalemleri')
    with op.batch_alter_table('cilek_fertigasyon_tanklari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_fertigasyon_tanklari_parsel_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_fertigasyon_tanklari_id'))

    op.drop_table('cilek_fertigasyon_tanklari')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queries_org_id'))
        batch_op.drop_index(batch_op.f('ix_queries_id'))
        batch_op.drop_index(batch_op.f('ix_queries_created_at'))

    op.drop_table('queries')
    with op.batch_alter_table('ikas_baglanti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ikas_baglanti_org_id'))
        batch_op.drop_index(batch_op.f('ix_ikas_baglanti_id'))

    op.drop_table('ikas_baglanti')
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_profiles_sektor'))
        batch_op.drop_index(batch_op.f('ix_financial_profiles_org_id'))
        batch_op.drop_index(batch_op.f('ix_financial_profiles_id'))

    op.drop_table('financial_profiles')
    with op.batch_alter_table('cilek_soguk_zincir_okumalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_soguk_zincir_okumalari_org_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_soguk_zincir_okumalari_olcum_zamani'))
        batch_op.drop_index(batch_op.f('ix_cilek_soguk_zincir_okumalari_id'))

    op.drop_table('cilek_soguk_zincir_okumalari')
    with op.batch_alter_table('cilek_parseller', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_parseller_org_id'))
        batch_op.drop_index(batch_op.f('ix_cilek_parseller_id'))

    op.drop_table('cilek_parseller')
    with op.batch_alter_table('tesvikler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tesvikler_kurum'))
        batch_op.drop_index(batch_op.f('ix_tesvikler_id'))
        batch_op.drop_index(batch_op.f('ix_tesvikler_guncelleme_tarihi'))
        batch_op.drop_index(batch_op.f('ix_tesvikler_baslik'))

    op.drop_table('tesvikler')
    with op.batch_alter_table('sector_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_benchmarks_sektor'))
        batch_op.drop_index(batch_op.f('ix_sector_benchmarks_id'))

    op.drop_table('sector_benchmarks')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_email'))
        batch_op.drop_index(batch_op.f('ix_organizations_created_at'))

    op.drop_table('organizations')
    with op.batch_alter_table('macro_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_indicators_id'))
        batch_op.drop_index(batch_op.f('ix_macro_indicators_anahtar'))

    op.drop_table('macro_indicators')
    with op.batch_alter_table('kurum_iletisim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kurum_iletisim_kurum'))
        batch_op.drop_index(batch_op.f('ix_kurum_iletisim_id'))

    op.drop_table('kurum_iletisim')
    with op.batch_alter_table('il_tarim_mudurlugu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_il_tarim_mudurlugu_il_kodu'))
        batch_op.drop_index(batch_op.f('ix_il_tarim_mudurlugu_il_adi'))
        batch_op.drop_index(batch_op.f('ix_il_tarim_mudurlugu_id'))

    op.drop_table('il_tarim_mudurlugu')
    with op.batch_alter_table('il_kosgeb_mudurlugu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_il_kosgeb_mudurlugu_il_kodu'))
        batch_op.drop_index(batch_op.f('ix_il_kosgeb_mudurlugu_il_adi'))
        batch_op.drop_index(batch_op.f('ix_il_kosgeb_mudurlugu_id'))

    op.drop_table('il_kosgeb_mudurlugu')
    with op.batch_alter_table('ihracat_fiyatlari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ihracat_fiyatlari_urun_adi'))
        batch_op.drop_index(batch_op.f('ix_ihracat_fiyatlari_tarih'))
        batch_op.drop_index(batch_op.f('ix_ihracat_fiyatlari_id'))

    op.drop_table('ihracat_fiyatlari')
    with op.batch_alter_table('hal_fiyatlari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hal_fiyatlari_urun_adi'))
        batch_op.drop_index(batch_op.f('ix_hal_fiyatlari_tarih'))
        batch_op.drop_index(batch_op.f('ix_hal_fiyatlari_id'))

    op.drop_table('hal_fiyatlari')
    with op.batch_alter_table('cilek_pazar_fiyatlari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cilek_pazar_fiyatlari_tarih'))
        batch_op.drop_index(batch_op.f('ix_cilek_pazar_fiyatlari_id'))

    op.drop_table('cilek_pazar_fiyatlari')
    # ### end Alembic commands ###
